### ISSUE TITLE
Milestone 2: reflection

### ISSUE THREAD

**Issue by Lorraine97** [UBC-MDS/climadash#18]
Plot 1: 

Plot 2: 

Plot 3:

Plot 4:

**Comment by xFiveRivers** [comment]
Here are some thoughts for the reflection:

- All plots have been added and core input widgets
- Still need to add interactivity with the plots (hover, brush, etc.)
- Move plot legend such that it doesn't interfere with the plot sizes (single unified legend, perhaps instead of a legend we can change the colors in the cities selection box to match the graphs?)
- Maybe add another complex addition (add map of Canada showing max and min per city)
- Fix the axis scales such that the display the years correctly when filtered in the data using the slider
- Add more colours/graphics to make the app more visually appealing (currently looks very boring)

**Comment by kellywujy** [comment]
@xFiveRivers Could you elaborate on "Fix the axis scales such that the display the years correctly when filtered in the data using the slider"? Current behavior is that the scale will match user's selected range of years.
All other points addressed in the reflection doc.
